version: '3.8'

# Создаем общую сеть default для всех контейнеров
networks:
  default:
    driver: bridge

services:
  database:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - default
    volumes:
      - ./docker/database/mysql/data:/var/lib/mysql

  php-fpm:
    build:
      context: ./docker/php-fpm
    depends_on:
      - database
    networks:
      - default
    volumes:
      - .:/var/www

  listener:
    build:
      context: ./docker/listener
    deploy:
      replicas: 3
    networks:
      - default
    volumes:
      - .:/var/www

  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "80:80"